import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClientWrapper } from "./ClientWrapper";
import { ApolloWrapper } from "@/lib/apolloClient";
import { SolanaConnectionProvider } from "./context/solanaConnectionContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "dscvr:canvas:version": "vNext",
    "og:image": "https://my-canvas.com/preview-image.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <ClientWrapper>
            <SolanaConnectionProvider>{children}</SolanaConnectionProvider>
          </ClientWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
}
